// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using TuiGroupFlights.Data;

namespace TuiGroupFlights.Migrations
{
    [DbContext(typeof(TuiGroupFlightsContext))]
    partial class TuiGroupFlightsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TuiGroupFlights.Models.Airport", b =>
                {
                    b.Property<int>("AirportID")
                        .ValueGeneratedOnAdd();

                    b.Property<float>("Longitude");

                    b.Property<string>("Name");

                    b.Property<float>("latitude");

                    b.HasKey("AirportID");

                    b.ToTable("Airport");
                });

            modelBuilder.Entity("TuiGroupFlights.Models.Flight", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("DestinyAirportId");

                    b.Property<int>("OriginAirportId");

                    b.HasKey("ID");

                    b.ToTable("Flight");
                });
#pragma warning restore 612, 618
        }
    }
}
